import { ActionCellField, AttachmentCellField, CheckboxCellField, CurrencyCellField, DateCellField, EmailCellField, LargeTextCellField, NumberCellField, SearchCellField, SelectCellField, TextCellField } from "@tq/tq-elements";

export interface Evaluacion {
    unidadProductiva: string,
    comprador: string,
    compradorId: string,
    proveedor: string,
    proveedorId: string,
    periodo: string,
    numOc: number,
    indicadorFecha: number,
    indicadorCantidad: number,
    indicadorCalidad: number,
    indicadorCumplimiento: number,
    estado: number,
    ordenCompraId: string,
    evaluacionId: string
}

export interface DetalleOc {
    id: string,
    proveedor: string,
    numOc: string,
    periodo: string,
    codigo: string,
    descripcion: string,
    unidadMedida: string,
    tipoInsumo: string,
    moneda: string,
    fechaCreacion: Date,
    fechaDespacho: Date,
    fechaRecibo: Date,
    ltm: number,
    ltc: number,
    ltr: number,
    dias: number,
    diasAtraso: number,
    cantidadPedida: number,
    cantidadAceptada: number,
    cantidadDevuelta: number,
    indicadorFecha: number,
    indicadorFechaSys: number,
    indicadorCantidad: number,
    indicadorCantidadSys: number,
    indicadorCalidad: number,
    indicadorCalidadSys: number,
    cumplimiento: number,
    urgencia: string,
    consignado: string,
    causalId: string | null,
    codigoCausal: number | null,
    comentario: string | null,
    compraDesarrollo: boolean,
    rechazo: string
}

export interface Filtros {
    proveedor: string[] | null,
    comprador: string[] | null,
    periodo: string | null,
    unidadProductiva: string | null,
    indicadorCantidad: number | null,
    indicadorCalidad: number | null,
    consignado: string | null,
    indicadorDesempeno: string | null,
    indicadorFecha: number | null,

}

export interface EvaluacionOC {
    id: string | null,
    seleccionado:boolean,
    campo1: string | null,
    campo2: string | null,
    campo3: string | null,
    campo4: string | null,
    campo5: string | null,
    campo6: string | null,
    campo7: string | null,
    campo8: string | null,
    campo9: string | null,
    campo10: string | null,
    parametroId: string | undefined
}

export interface DetallesAll {
    id: string,
    seleccionado:boolean,
    proveedor: string,
    proveedorId: string,
    codigoInsumo: string,
    descripcionInsumo: string,
    numOc: string,
    comprador: string,
    compradorId: string,
    periodo: string,
    unidadProductiva: string,
    fechaCreacion: Date,
    ltm: number,
    ltc: number,
    ltr: number,
    dias: number,
    diasAtraso: number,
    indicadorFecha: number,
    indicadorFechaSys: number,
    cantidadPedida: number,
    cantidadRecibida: number,
    indicadorCantidad: number,
    indicadorCantidadSys: number,
    estadoLote: string,
    numeroLote: string,
    indicadorCalidad: number,
    indicadorCalidadSys: number,
    indicadorCumplimiento: number,
    estado: number,
    ordenCompraId: string,
    causalId: string | null,
    codigoCausal: number | null,
    comentario: string | null,
    compraDesarrollo: boolean | null
}
  